#!/bin/bash

clear

function all {
audit
bum
disable-guest
disable-ipv6
find-things
firewall
pass-reset
policy
secure-root
security
ssh-conf
misc
read -p "Perform update right now? [y/n]   " update
while !([ $update == "y" ] || [ $update == "yes" ] || [ $update == "Y" ] || [ $update == "YES" ] || [ $update == "Yes" ] || [ $update == "n" ] || [ $update == "no" ] || [ $update == "N" ] || [ $update == "NO" ] || [ $update == "No" ])
do
	read -p "Perform update right now? [y/n]   " update
done
if ([ $update == "y" ] || [ $update == "yes" ] || [ $update == "Y" ] || [ $update == "YES" ] || [ $update == "Yes" ])
then
	sys-update
fi
echo -e "\033[1mEverything done.\033[0m"
sleep 1.5
clear
}

function audit {
apt-get -y install auditd
auditctl -e 1
}

function bum {
apt-get -y install bum
bum
}

function disable-guest {
if ! grep "allow-guest=false" /usr/share/lightdm/lightdm.conf.d/50-ubuntu.conf > /dev/null
then
	echo "allow-guest=false" >> /usr/share/lightdm/lightdm.conf.d/50-ubuntu.conf
fi
echo -e "\033[1mGuest account is disabled.\033[0m"
sleep 1.5
}

function disable-ipv6 {
sed -i -e "s/alias net-pf-10 off/alias ipv6 off/" /etc/modprobe.d/aliases
echo -e "\033[1mIPv6 is disabled.\033[0m"
sleep 1
}

function end {
echo -e "\033[1mStay gold.\033[0m"
sleep 1
clear
exit
}

function find-things {
for program in apache2 bind9 cain cracklib hydra john nc netcat nginx nikto postgresql samba telnet tftp-server vsftpd
do
	which $program >> output
done
for files in *.jpg *.mp3 *.mp4 *.png
do
	find /home -name $files >> output
done
echo -e "\033[1mSuspicious programs and files have been printed to the output file.\033[0m"
sleep 1.5
}

function firewall {
apt-get -y install ufw
ufw enable
echo -e "\033[1mFirewall has been enabled.\033[0m"
sleep 1.5
}

function help {
sed -n -e 35,95p README.md | less
}

function misc {
for permissions in /etc/hosts.allow /etc/mtab /etc/profile /etc/syslog.pid /etc/utmp /var/adm/wtmp /var/log/wtmp /var/run/syslog.pid /etc/inittab /etc/sysctl.conf
do
	chmod -R -f 700 $permissions
done
# make sure nothing is in the rc.local file
for etc in /etc/rc.local /etc/resolv.conf /etc/hosts /etc/passwd /etc/shadow
do
	nano $etc
done
echo "vm.swappiness=1" >> /etc/sysctl.conf
sed -i -e "s/expose_php on/expose_php off/" /etc/php.config
echo -e "\033[1mMiscellaneous things have been done.\033[0m"
sleep 1.5
}

function pass-reset {
ls /home > users
read -s -p "What should the default password be?	" defpass
echo ""
read -s -p "Retype the password to confirm.	" confirm
echo ""
while !([ "$defpass" == "$confirm" ])
do
	echo "The password entered did not match"
	read -s -p "What should the default password be?	" defpass
	echo ""
	read -s -p "Retype the password to confirm.	" confirm
	echo ""
done
cat users | while read users
do
	echo $users:$defpass | chpasswd
done
unset defpass
unset confirm
rm users
echo -e "\033[1mDefault password has been set.\033[0m"
sleep 1.5
}

function policy {
sed -i -e "s/obscure sha512/obscure sha512 minlen=12 retry=3 remember=5/" /etc/pam.d/common-password
sed -i -e "s/PASS_MAX_DAYS	99999/PASS_MAX_DAYS	60/" /etc/login.defs
sed -i -e "s/PASS_MIN_DAYS	60/PASS_MIN_DAYS	59/" /etc/login.defs
echo -e "\033[1mPassword policy has been set.\033[0m"
echo "auth required pam_tally2.so deny=5 onerr=fail unlock_time=1800" >> /etc/pam.d/common-auth
echo -e "\033[1mAccount policy has been set.\033[0m"
sleep 1.5
}

function secure-root {
passwd -l root
echo -e "\033[1mRoot account password secured.\033[0m"
sleep 1.5
}

function security {
for installs in apparmor bastille chkrootkit clamav lynis rkhunter
do
	apt-get -y install $installs
done
/usr/sbin/chkrootkit > chkrootkit
bastille -c
echo -e "\033[1mapparmor, bastille, chkrootkit, clamav, lynis, and rkhunter have been installed.\033[0m"
echo -e "\033[1mchkrootkit and bastille have been enabled.\033[0m"
sleep 2
}

function ssh-conf {
sed -i -e "s/PasswordAuthentication yes/PasswordAuthentication no/" /etc/ssh/ssh_config
sed -i -e "s/PermitRootLogin yes/PermitRootLogin no/" /etc/ssh/sshd_config
sed -i -e "s/# Port 22/Port 222/" /etc/ssh/sshd_config
service sshd restart
echo -e "\033[1mSSH and SSHD policies have been set.\033[0m"
echo -e "\033[1mSSH is now on port 222.\033[0m"
sleep 1.5
}

function sys-update {
read -p "Update policy has been properly set? [y/n] " policy
while !([ $policy == "y" ] || [ $policy == "yes" ] || [ $policy == "Y" ] || [ $policy == "YES" ] || [ $policy == "Yes" ])
do
	echo "Go set it."
	read -p "Update policy has been properly set? [y/n] " policy
done
apt-get -y update
apt-get -y upgrade
echo -e "\033[1mSystem has been updated.\033[0m"
sleep 1.5
}

while true
do
clear
echo "Your options are"
echo -e " all\n audit\n bum\n disable-guest\n disable-ipv6\n end\n find-things\n firewall\n help\n misc\n pass-reset\n policy\n secure-root\n security\n ssh-conf\n sys-update"
read -p "What do?   " action
clear
$action
done
